### ISSUE TITLE
Bad call to okhttp3.RequestBody.create causes NoSuchMethodError

### ISSUE THREAD

**Issue by franck102** [apimatic/okhttp-client-adapter#45]
Hi all,

maven/io.apimatic/okhttp-client-adapter@0.1.6 has a dependency on com.squareup.okhttp3:okhttp:4.10.0

According to this page
[OkClient.java](https://github.com/apimatic/okhttp-client-adapter/blob/main/src/main/java/io/apimatic/okhttpclient/adapter/OkClient.java)

at line 210 the apimatic client adapter calls RequestBody.create(content, mediaType).

There is no such method in okhttp3, the correct signature is create(mediaType, content).

Related issue: [https://github.com/square/square-java-sdk/issues/104](https://github.com/square/square-java-sdk/issues/104)

**Comment by asadali214** [comment]
Hi @frnck102

  Thanks for highlighting this issue. We'll look into this and circle back soon.

  Cheer!

**Comment by asadali214** [comment]
It appears that you have already resolved this issue based on your feedback [here](https://github.com/square/square-java-sdk/issues/104#issuecomment-1582099624) using the latest alpha version `com.squareup.okhttp3 : 5.0.0-alpha.11` along with `square` dependency.
``` xml
<dependency>
   <groupId>com.squareup</groupId>
   <artifactId>square</artifactId>
   <version>28.0.0.20230419</version>
   <scope>compile</scope>
</dependency>
<dependency>
   <groupId>com.squareup.okhttp3</groupId>
   <artifactId>okhttp</artifactId>
   <version>5.0.0-alpha.11</version>
</dependency>
```
Hence, we are marking this issue as closed. Feel free to re-open the issue anytime you face such an exception again.

**Comment by franck102** [comment]
I haven't quite resolved this issue since my SendInBlue APIs are broken due to the exclusions I had to introduce as mentioned in [that other post](https://github.com/square/square-java-sdk/issues/104#issuecomment-1582099624).
